FROM node:7
ARG BUILD_ARG
ARG COMMIT
ARG BUILD_DATE
ENV BUILD_NUM=${BUILD_ARG}
ENV COMMIT=${COMMIT}
ENV BUILD_DATE=${BUILD_DATE}
ENV RESPOSNSE_MSG="Not defined - Default"
ADD app.js /app.js
ENTRYPOINT ["node", "app.js"]