name: BuildAndPush

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Output Run Number
        run: echo ${{ github.run_number }}
      - name: Extract branch name
        shell: bash
        run: echo "REF - ${GITHUB_REF}     REF filtered - ${GITHUB_REF#refs/heads/}"
      - name: Test
        run: echo "${BRANCH_NAME}"  
      -
        name: Build and push
        id: docker_build
        build-args:
          - name: BUILD_NUM
            value: ${{ github.run_number }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: amisovic/kubia:${{ github.run_number }}
