name: BuildAndPush

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date and test how GITHUB_OUTPUT works
        id: dateee
        run: | 
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "varijabla=PERICA" >> $GITHUB_OUTPUT
          cat  $GITHUB_OUTPUT
      - name: Test with environment variables
        env:
          TAG_NAME: date-tag-${{ steps.dateee.outputs.date }}
          RELEASE_NAME: custom-release-${{ steps.dateee.outputs.varijabla }}
          run: echo $TAG_NAME - $RELEASE_NAME
      - name: Output Some variables 
        run: | 
          echo ${{ github.run_number }}
          echo ${{ github.sha }}
          echo ${{ steps.dateee.outputs.date }} 
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "REF - ${GITHUB_REF}     REF filtered - ${GITHUB_REF#refs/heads/}"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: amisovic/kubia:${{ github.run_number }}
          build-args: |
            BUILD_ARG=${{ github.run_number }}
            COMMIT=${{ github.sha }}
            BUILD_DATE=${{ steps.dateee.outputs.date }} 
      - name: Push to kubiacd repo - for ArgoCD to pick up the change
        env:
          GITHUBACT_TOKEN: ${{ secrets.GITHUBACTIONS_TOKEN }}
          BUILD_NUMBER: ${{ github.run_number }}
        run: |
          echo "Checkout repo kubiacd."
          git clone https://amisovic:$GITHUBACT_TOKEN@github.com/amisovic/kubiacd.git 
         
          cd kubiacd
          git config user.name "Aleksandar Misovic"
          git config user.email "aleksandar.misovic72@gmail.com"
          sed -i "s/        image: amisovic\/kubia:.*/        image: amisovic\/kubia:${BUILD_NUMBER}/" argocd/deployment.yaml
          echo "Add edited file and push to kubiacd repo."
          git add argocd/deployment.yaml
          git commit -m "Updated to version for new build: ${BUILD_NUMBER} "

          git remote -v 

          git push  